version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    networks:
      - my-net  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 30s
      retries: 5
    command: ["redis-server"]
    networks:
            - my-net
  s3upload:
    build:
      context: ./server/S3Upload
      dockerfile: Dockerfile
    env_file:
      - .env  
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    networks:
      - my-net
    restart : always
  videoprocessing-worker:
    build:
      context: ./server/VideoProcessing
      dockerfile: Dockerfile
    env_file:
      - .env  
    depends_on:
      - postgres
      - redis
    networks:
      - my-net
    restart : always 
networks:
    my-net: 
      driver: bridge